[2022-07-12 20:39:11,144] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-13.validate_kaggle_login scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 20:39:11,157] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-13.validate_kaggle_login scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 20:39:11,157] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:39:11,157] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-07-12 20:39:11,157] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:39:11,170] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): validate_kaggle_login> on 2022-07-11 00:00:00+00:00
[2022-07-12 20:39:11,176] {standard_task_runner.py:52} INFO - Started process 1844 to run task
[2022-07-12 20:39:11,181] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_project_dag-13', 'validate_kaggle_login', 'scheduled__2022-07-11T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmpfxr0ulrg', '--error-file', '/tmp/tmpngd3pirw']
[2022-07-12 20:39:11,186] {standard_task_runner.py:77} INFO - Job 46: Subtask validate_kaggle_login
[2022-07-12 20:39:11,295] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_project_dag-13.validate_kaggle_login scheduled__2022-07-11T00:00:00+00:00 [running]> on host b7c97f870ea6
[2022-07-12 20:39:11,421] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_project_dag-13
AIRFLOW_CTX_TASK_ID=validate_kaggle_login
AIRFLOW_CTX_EXECUTION_DATE=2022-07-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-11T00:00:00+00:00
[2022-07-12 20:39:11,423] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-12 20:39:11,424] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/usr/bin\n\nexport KAGGLE_USERNAME=yusufkamorudeen\nexport KAGGLE_KEY=f9e7d64641f620123ab335c78451fdf4\n\n\n#dataset_id=mashlyn/online-retail-ii-uci\n#data_name=online-retail-ii-uci.zip\n\n\n\n\n#mv $data_name uk_housing.zip\n\n\n']
[2022-07-12 20:39:11,442] {subprocess.py:85} INFO - Output:
[2022-07-12 20:39:11,445] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-12 20:39:11,484] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_project_dag-13, task_id=validate_kaggle_login, execution_date=20220711T000000, start_date=20220712T203911, end_date=20220712T203911
[2022-07-12 20:39:11,519] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-12 20:39:11,573] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
