[2022-07-13 20:32:35,212] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-12T00:00:00+00:00 [queued]>
[2022-07-13 20:32:35,223] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-12T00:00:00+00:00 [queued]>
[2022-07-13 20:32:35,224] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 20:32:35,224] {taskinstance.py:1239} INFO - Starting attempt 11 of 12
[2022-07-13 20:32:35,224] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 20:32:35,237] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-12 00:00:00+00:00
[2022-07-13 20:32:35,243] {standard_task_runner.py:52} INFO - Started process 157 to run task
[2022-07-13 20:32:35,248] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_project_dag-12', 'download_dataset_task', 'scheduled__2022-07-12T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmpopqyu78a', '--error-file', '/tmp/tmpd_w96nzp']
[2022-07-13 20:32:35,249] {standard_task_runner.py:77} INFO - Job 110: Subtask download_dataset_task
[2022-07-13 20:32:35,347] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-12T00:00:00+00:00 [running]> on host 1baccf4ebc57
[2022-07-13 20:32:35,527] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_project_dag-12
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-12T00:00:00+00:00
[2022-07-13 20:32:35,529] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-13 20:32:35,531] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/usr/bin\npip install kaggle\n\nexport KAGGLE_USERNAME=yusufkamorudeen\nexport KAGGLE_KEY=f9e7d64641f620123ab335c78451fdf4\n\n\n\n\n\nDATASET_ID=cheneblanc\nDATASET_NAME=housing-prices-35-fr\n\nkaggle datasets download -d $DATASET_ID/$DATASET_NAME --unzip -p "/opt/***/$DATASET_ID"\n\n\n\n\n\n']
[2022-07-13 20:32:35,558] {subprocess.py:85} INFO - Output:
[2022-07-13 20:32:36,319] {subprocess.py:89} INFO - Defaulting to user installation because normal site-packages is not writeable
[2022-07-13 20:32:36,705] {subprocess.py:89} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.7/site-packages (1.5.12)
[2022-07-13 20:32:36,717] {subprocess.py:89} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.0.1)
[2022-07-13 20:32:36,718] {subprocess.py:89} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.26.0)
[2022-07-13 20:32:36,719] {subprocess.py:89} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2020.12.5)
[2022-07-13 20:32:36,720] {subprocess.py:89} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.16.0)
[2022-07-13 20:32:36,721] {subprocess.py:89} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.8.2)
[2022-07-13 20:32:36,724] {subprocess.py:89} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.26.7)
[2022-07-13 20:32:36,726] {subprocess.py:89} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.64.0)
[2022-07-13 20:32:36,768] {subprocess.py:89} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify->kaggle) (1.3)
[2022-07-13 20:32:36,862] {subprocess.py:89} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (3.3)
[2022-07-13 20:32:36,866] {subprocess.py:89} INFO - Requirement already satisfied: charset-normalizer~=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (2.0.9)
[2022-07-13 20:32:43,970] {subprocess.py:89} INFO - WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
[2022-07-13 20:32:43,971] {subprocess.py:89} INFO - You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[2022-07-13 20:32:45,671] {subprocess.py:89} INFO - Downloading housing-prices-35-fr.zip to /opt/***/cheneblanc
[2022-07-13 20:32:49,947] {subprocess.py:89} INFO -   0%|          | 0.00/21.6M [00:00<?, ?B/s]  5%|▍         | 1.00M/21.6M [00:00<00:03, 7.14MB/s]  9%|▉         | 2.00M/21.6M [00:00<00:02, 8.03MB/s] 19%|█▊        | 4.00M/21.6M [00:00<00:01, 9.85MB/s] 23%|██▎       | 5.00M/21.6M [00:01<00:05, 3.43MB/s] 28%|██▊       | 6.00M/21.6M [00:01<00:03, 4.31MB/s] 32%|███▏      | 7.00M/21.6M [00:01<00:02, 5.14MB/s] 37%|███▋      | 8.00M/21.6M [00:01<00:02, 5.88MB/s] 46%|████▋     | 10.0M/21.6M [00:01<00:01, 7.56MB/s] 56%|█████▌    | 12.0M/21.6M [00:01<00:01, 8.50MB/s] 60%|██████    | 13.0M/21.6M [00:02<00:01, 8.82MB/s] 69%|██████▉   | 15.0M/21.6M [00:02<00:00, 9.21MB/s] 74%|███████▍  | 16.0M/21.6M [00:02<00:00, 9.42MB/s] 79%|███████▊  | 17.0M/21.6M [00:02<00:00, 9.44MB/s] 83%|████████▎ | 18.0M/21.6M [00:02<00:00, 9.48MB/s] 93%|█████████▎| 20.0M/21.6M [00:02<00:00, 9.77MB/s]100%|██████████| 21.6M/21.6M [00:02<00:00, 9.82MB/s]100%|██████████| 21.6M/21.6M [00:02<00:00, 7.72MB/s]
[2022-07-13 20:32:49,951] {subprocess.py:89} INFO - 
[2022-07-13 20:32:50,049] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-13 20:32:50,114] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_project_dag-12, task_id=download_dataset_task, execution_date=20220712T000000, start_date=20220713T203235, end_date=20220713T203250
[2022-07-13 20:32:50,190] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-13 20:32:50,266] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
