[2022-07-13 10:24:53,282] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-12T00:00:00+00:00 [queued]>
[2022-07-13 10:24:53,296] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-12T00:00:00+00:00 [queued]>
[2022-07-13 10:24:53,296] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 10:24:53,297] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-07-13 10:24:53,297] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 10:24:53,315] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-12 00:00:00+00:00
[2022-07-13 10:24:53,322] {standard_task_runner.py:52} INFO - Started process 2166 to run task
[2022-07-13 10:24:53,331] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_project_dag-12', 'download_dataset_task', 'scheduled__2022-07-12T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmph7ttux_3', '--error-file', '/tmp/tmp17izanh_']
[2022-07-13 10:24:53,333] {standard_task_runner.py:77} INFO - Job 8: Subtask download_dataset_task
[2022-07-13 10:24:53,424] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-12T00:00:00+00:00 [running]> on host 1baccf4ebc57
[2022-07-13 10:24:53,557] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_project_dag-12
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-12T00:00:00+00:00
[2022-07-13 10:24:53,559] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-13 10:24:53,560] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/usr/bin\npip install kaggle\n\nexport KAGGLE_USERNAME=yusufkamorudeen\nexport KAGGLE_KEY=f9e7d64641f620123ab335c78451fdf4\n\n\n\n\n\nDATASET_ID=mashlyn\nDATASET_NAME=online-retail-ii-uci\nFILE_NAME=$DATASET_NAME.csv\n\n\nkaggle datasets download -d $DATASET_ID/$DATASET_NAME --unzip  -p "/opt/***/$DATASET_ID/$DATASET_NAME"\n\n\n\n\n\n#mv $data_name uk_housing.zip\n\n\n']
[2022-07-13 10:24:53,584] {subprocess.py:85} INFO - Output:
[2022-07-13 10:24:54,315] {subprocess.py:89} INFO - Defaulting to user installation because normal site-packages is not writeable
[2022-07-13 10:24:54,393] {subprocess.py:89} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.7/site-packages (1.5.12)
[2022-07-13 10:24:54,400] {subprocess.py:89} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.26.0)
[2022-07-13 10:24:54,400] {subprocess.py:89} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.8.2)
[2022-07-13 10:24:54,401] {subprocess.py:89} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.64.0)
[2022-07-13 10:24:54,401] {subprocess.py:89} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.0.1)
[2022-07-13 10:24:54,402] {subprocess.py:89} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.26.7)
[2022-07-13 10:24:54,403] {subprocess.py:89} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.16.0)
[2022-07-13 10:24:54,403] {subprocess.py:89} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2020.12.5)
[2022-07-13 10:24:54,427] {subprocess.py:89} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify->kaggle) (1.3)
[2022-07-13 10:24:54,448] {subprocess.py:89} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (3.3)
[2022-07-13 10:24:54,451] {subprocess.py:89} INFO - Requirement already satisfied: charset-normalizer~=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (2.0.9)
[2022-07-13 10:24:59,919] {subprocess.py:89} INFO - WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
[2022-07-13 10:24:59,919] {subprocess.py:89} INFO - You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[2022-07-13 10:25:01,312] {subprocess.py:89} INFO - Downloading online-retail-ii-uci.zip to /opt/***/mashlyn/online-retail-ii-uci
[2022-07-13 10:25:03,275] {subprocess.py:89} INFO -   0%|          | 0.00/14.5M [00:00<?, ?B/s]  7%|▋         | 1.00M/14.5M [00:00<00:01, 7.84MB/s] 21%|██        | 3.00M/14.5M [00:00<00:01, 11.7MB/s] 34%|███▍      | 5.00M/14.5M [00:00<00:00, 12.7MB/s] 48%|████▊     | 7.00M/14.5M [00:00<00:00, 13.2MB/s] 62%|██████▏   | 9.00M/14.5M [00:00<00:00, 12.8MB/s] 76%|███████▌  | 11.0M/14.5M [00:00<00:00, 13.2MB/s] 90%|████████▉ | 13.0M/14.5M [00:01<00:00, 13.1MB/s]100%|██████████| 14.5M/14.5M [00:01<00:00, 13.6MB/s]100%|██████████| 14.5M/14.5M [00:01<00:00, 13.0MB/s]
[2022-07-13 10:25:03,275] {subprocess.py:89} INFO - 
[2022-07-13 10:25:03,474] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-13 10:25:03,520] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_project_dag-12, task_id=download_dataset_task, execution_date=20220712T000000, start_date=20220713T102453, end_date=20220713T102503
[2022-07-13 10:25:03,548] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-13 10:25:03,598] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
